import streamlit as st
import chess
import chess.svg
import joblib
import numpy as np

from src.move_generator import get_candidate_moves
from src.feature_extractor import extract_features
from src.human_ranker import rank_moves
from src.explainer import explain_move

# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(
    page_title="Human-Centric Chess Tutor",
    layout="wide"
)

# ===============================
# LOAD MODELS
# ===============================
@st.cache_resource
def load_models():
    move_model = joblib.load("models/move_selector.pkl")
    risk_model = joblib.load("models/risk_classifier.pkl")
    return move_model, risk_model

move_model, risk_model = load_models()

# ===============================
# SIDEBAR
# ===============================
st.sidebar.title("♟️ Chess Tutor")

elo = st.sidebar.slider(
    "Your Elo",
    min_value=400,
    max_value=2000,
    value=1000,
    step=50
)

mode = st.sidebar.selectbox(
    "Mode",
    ["Practical Move", "Safe Move", "Learning Mode"]
)

fen = st.sidebar.text_area(
    "FEN Position",
    value=chess.STARTING_FEN,
    height=100
)

analyze = st.sidebar.button("Analyze Position")

# ===============================
# MAIN TITLE
# ===============================
st.title("♟️ Human-Centric Chess Tutor")
st.caption(
    "Practical chess advice learned from real human games — not engine lines."
)

# ===============================
# BOARD DISPLAY
# ===============================
try:
    board = chess.Board(fen)
    board_svg = chess.svg.board(board, size=400)
    st.components.v1.html(board_svg, height=420)
except:
    st.error("Invalid FEN")
    st.stop()

# ===============================
# ANALYSIS PIPELINE
# ===============================
if analyze:
    with st.spinner("Analyzing position..."):

        # 1️⃣ Candidate moves (Stockfish = safety filter)
        candidate_moves = get_candidate_moves(fen)

        if len(candidate_moves) == 0:
            st.warning("No reasonable moves found.")
            st.stop()

        # 2️⃣ Feature extraction
        move_data = []
        for mv in candidate_moves:
            feats = extract_features(fen, mv, elo)
            move_data.append({
                "move": mv,
                "features": feats
            })

        # 3️⃣ Human-centric ranking
        ranked = rank_moves(
            move_data,
            move_model,
            risk_model,
            mode
        )

        best = ranked[0]
        rejected = ranked[1:4]

    # ===============================
    # OUTPUT
    # ===============================
    st.subheader("✅ Recommended Move")
    st.markdown(f"### **{best['move']}**")
    st.progress(min(best["confidence"] / 100, 1.0))
    st.caption(f"Human Practicality Score: {best['confidence']} / 100")

    explanation = explain_move(best, rejected, elo)

    st.markdown("### 🧠 Why this move?")
    st.write(explanation["why_best"])

    st.markdown("### ❌ Why not other moves?")
    for txt in explanation["why_not"]:
        st.write(f"- {txt}")

    if mode == "Learning Mode":
        st.markdown("### 📘 Learning Tip")
        st.info(explanation["learning_tip"])

# ===============================
# FOOTER
# ===============================
st.markdown("---")
st.caption(
    "Stockfish is used only to verify move soundness. "
    "Final decisions and explanations are generated by a human-centric ML model "
    "trained on the Lichess dataset."
)
